version: 2
updates:
  - package-ecosystem: "npm"  # Specify the package ecosystem (npm for Angular)
    directory: "/"            # Location of package manifests (root directory)

    # Configure update schedule (optional)
    schedule:
      interval: "weekly"      # Check for updates weekly

    # Optionally, you can specify additional configuration
    # For example, ignore certain dependencies or customize update behavior
    # Example:
    # ignore:
    #   - dependency-name
    #   - another-dependency-name
    # commit-message:
    #   prefix: "chore(deps):"  # Customize commit message prefix

    # Security updates (optional)
    # Allow Dependabot to automatically merge security updates
    # security:
    #   automerge: true

    # Labels (optional)
    # Assign labels to Dependabot pull requests
    # labels:
    #   - "dependencies"
    #   - "automated"

    # Reviewers (optional)
    # Request reviews from specific users or teams for Dependabot pull requests
    # reviewers:
    #   - username: user1
    #   - team: team1
